### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/graphql-server#113]
- [x] Create a branch for the release **Branch `release-v1.2.0`**
- [x] Update the dependencies. The dependabot PR backlog is not comprehensive and doesn't include transitive dependencies, and merging them one at a time tends to break things, so the best way to do this is manually with npm. **Done in #114**
- [x] Bump the `intermineVersion` in `data-sources/intermine/api/index.ts` if appropriate. **N/A**
- [x] Update the base image version in the `Dockerfile` if necessary (this should be the most recent node LTS version) and do a test build and run of the Docker image on you local machine so you know if something is going to go off the rails before the automated build action on GitHub. **Done in #114**
- [x] Update the GHCR image tag in `compose.prod.yml` to the imminent release version **Done in commit dfa1ca54d645c597aebf9b11b99dda82fa113cc1**
- [x] Bump the `"version"` number in `package.json`. **Done in commit 5b696fdbf61caad44d655193cf7f5a8f5b7ef6aa**
- [x] Open a PR that merges the release branch into main. **#115**
- [x] Merge the release PR after it passes testing and review.
- [x] Tag a corresponding release on GitHub. This will trigger an automated Docker image build on GitHub. If the build succeeds it will be automatically published to GHCR.
