### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/graphql-server#96]
- [x] Create a branch for the release **Branch "v1.1.0"**
- [x] Update the dependencies. The dependabot PR backlog is not comprehensive and doesn't include transitive dependencies, and merging them one at a time tends to break things, so the best way to do this is manually with npm. **Done in PR #95**
- [x] Bump the `intermineVersion` in `data-sources/intermine/api/index.ts` if appropriate. **Done in PR #67**
- [x] Update the base image version in the `Dockerfile` if necessary (this should be the most recent node LTS version) and do a test build and run of the Docker image on you local machine so you know if something is going to go off the rails before the automated build action on GitHub. **Done in PR #98**
- [x] Update the GHCR image tag in `compose.prod.yml` to the imminent release version **Done in commit 2a9f6812de0d86c97c9dbcfb74534383a49eac44**
- [x] Bump the `"version"` number in `package.json`. **Done in  commit 881df8a8d5ce76d8b636b4058bc16908ba0d14bd**
- [x] Open a PR that merges the release branch into main. **PR #99**
- [x] Merge the release PR after it passes testing and review.
- [x] Tag a corresponding release on GitHub. This will trigger an automated Docker image build on GitHub. If the build succeeds it will be automatically published to GHCR.

**Comment by alancleary** [comment]
Release v1.1.0 has been tagged and the Docker image was automatically built and uploaded to GHCR. Closing.
